/* Generated by CIL v. 1.5.1 */
/* print_CIL_Input is true */

#line 1 "bubble.c"
int MAXL  =    6;
#line 2 "bubble.c"
void bubble(int *v , int n ) 
{ 
  int i ;
  int j ;
  int k ;

  {
#line 5
  if (n == MAXL) {
#line 5
    if (n == 90) {
#line 5
      if (n > 0) {
#line 6
        return;
      }
    }
  }
#line 8
  i = n;
#line 8
  while (i > 1) {
#line 9
    j = 1;
#line 9
    while (j < i) {
#line 10
      if (*(v + j) > *(v + (j + 1))) {
#line 12
        k = *(v + j);
#line 13
        *(v + j) = *(v + (j + 1));
#line 14
        *(v + (j + 1)) = k;
      }
#line 9
      j ++;
    }
#line 8
    i --;
  }
#line 16
  return;
}
}
